sylius 1.11 support
stefandoorn/google-tag-manager-plugin pull request #106
Opened 2022-04-06 17:12 UTC by tuxes3

2022-04-06 18:44 UTC, stefandoorn commented
Could you also add 1.11 to the GitHub Actions build matrix?

2022-04-07 19:44 UTC, tuxes3 commented
done

2022-04-09 15:04 UTC, Prometee requested changes

2022-04-09 15:04 UTC, Prometee commented on composer.json
> +        "sylius/sylius": "~1.9.0 || ~1.10.0 || ~1.11.0",
```suggestion
        "sylius/sylius": "^1.9",
```
It will avoid adding futur versions here until 2.0 will be release

2022-04-09 15:04 UTC, Prometee commented on composer.json
>          "php": "^7.4 || ^8.0",
@stefandoorn Sylius is already handling the PHP version so I think you can remove the php requirement, WDYT ?

2022-04-10 08:05 UTC, stefandoorn commented on composer.json
> +        "sylius/sylius": "~1.9.0 || ~1.10.0 || ~1.11.0",
I'm in doubt about this one. The downside is that CI does not upgrade automatically in a similar way, so we still have to add it to the build matrix each time. Although on the other hand it might also be handy to spot issues earlier, as users will upgrade their installations.

2022-04-10 08:05 UTC, stefandoorn commented on composer.json
>          "php": "^7.4 || ^8.0",
Yeah - that makes sense to me. No need to have them overlapping too much.

2022-04-11 16:54 UTC, Prometee commented on composer.json
> +        "sylius/sylius": "~1.9.0 || ~1.10.0 || ~1.11.0",
Majority of plugins are acting like that, you will block some upgrade plans if you try to list all new versions.
Right now for example, I'm forced to make my own fork of this plugin to continue to upgrade to Sylius 1.11.

If a dev is starting to develop with Sylius (latest version), he won't be allowed to tests your plugin because of this requirement.

Letting devs test the untested Sylius version is not a big deal I guess. If there is bug with this new version, then devs will likely create an issue and maybe helps you by making a PR.

2022-04-11 20:01 UTC, tuxes3 commented
The Actions should run through now 🤞

2022-04-12 19:14 UTC, stefandoorn commented on composer.json
> +        "sylius/sylius": "~1.9.0 || ~1.10.0 || ~1.11.0",
Yep - makes sense. I'll adjust it after this PR :-)

2022-04-12 19:18 UTC, stefandoorn commented
Somehow the 1.11 builds fail on a missing directory, is that something we need to copy from the plugin skeleton?

2022-04-12 20:58 UTC, Prometee commented
@stefandoorn yes : https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.11.md#api-platform-required-folders

2022-04-13 14:55 UTC, merged